Template-ize as many of the files as we can in preparation for Chef

diff --git a/templates/ec2ifdown.erb b/templates/ec2ifdown.erb
--- a/templates/ec2ifdown.erb
+++ b/templates/ec2ifdown.erb
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 # Copyright (C) 2012 Amazon.com, Inc. or its affiliates.
 # All Rights Reserved.
 #
@@ -13,5 +15,19 @@
 # specific language governing permissions and limitations under the
 # License.
 
-ACTION=="add", SUBSYSTEM=="net", KERNEL=="eth*", IMPORT{program}="/bin/sleep 1"
-SUBSYSTEM=="net", KERNEL=="eth*", RUN+="/etc/sysconfig/network-scripts/ec2net.hotplug"
+if [ "$#" -eq 1 ]; then
+  INTERFACE="${1}"
+else
+  echo "usage: ${0##*/} <device name>"
+  exit 1
+fi
+
+if [ $UID -ne 0 ]; then
+  echo "error: ${0##*/} must be run as root"
+  exit 1
+fi
+
+. <%= @network_scripts_dir %>/ec2net-functions
+
+deactivate_primary
+unplug_interface
diff --git a/templates/ec2ifscan.erb b/templates/ec2ifscan.erb
--- a/templates/ec2ifscan.erb
+++ b/templates/ec2ifscan.erb
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright (C) 2012 Amazon.com, Inc. or its affiliates.
+# Copyright (C) 2013 Amazon.com, Inc. or its affiliates.
 # All Rights Reserved.
 #
 # Licensed under the Apache License, Version 2.0 (the "License").
@@ -15,22 +15,17 @@
 # specific language governing permissions and limitations under the
 # License.
 
-# During init and before the network service is started, metadata is not
-# available. Exit without attempting to configure the elastic interface.
-if [ ! -f /var/lock/subsys/network ]; then
-  exit
-fi
-if [ -f /dev/.in_sysinit ]; then
-  exit
+if [ $UID -ne 0 ]; then
+  echo "error: ${0##*/} must be run as root"
+  exit 1
 fi
 
-. /etc/sysconfig/network-scripts/ec2net-functions
-
-case $ACTION in
-  add)
-    plug_interface
-    ;;
-  remove)
-    unplug_interface
-    ;;
-esac
+logger --tag ec2net "[ec2ifscan] Scanning for unconfigured interfaces"
+for dev in $(find /sys/class/net/eth*) ; do
+  cfg="<%= @ec2ifscan_dev_path %>"
+  state=$(cat ${dev}/operstate)
+  if [ ! -e "${cfg}" ] && [ "${state}" == "down" ] ; then
+    logger --tag ec2net "[ec2ifscan] Configuring ${dev##*/}"
+    echo 'add' > ${dev}/uevent
+  fi
+done
diff --git a/templates/ec2ifup.erb b/templates/ec2ifup.erb
--- a/templates/ec2ifup.erb
+++ b/templates/ec2ifup.erb
@@ -15,18 +15,19 @@
 # specific language governing permissions and limitations under the
 # License.
 
-INTERFACE="${interface}"
-PREFIX="${new_prefix}"
-. /etc/sysconfig/network-scripts/ec2net-functions
+if [ "$#" -eq 1 ]; then
+  INTERFACE="${1}"
+else
+  echo "usage: ${0##*/} <device name>"
+  exit 1
+fi
 
-ec2dhcp_config() {
-  rewrite_rules
-  # This can be done asynchronously, to save boot time
-  # since it doesn't affect the primary address
-  rewrite_aliases &
-}
+if [ $UID -ne 0 ]; then
+  echo "error: ${0##*/} must be run as root"
+  exit 1
+fi
 
-ec2dhcp_restore() {
-  remove_aliases
-  remove_rules
-}
+. <%= @network_scripts_dir %>/ec2net-functions
+
+plug_interface
+activate_primary
